CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Components/DepartmentSelectorViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CC98.TeacherEvaluationSystem.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.EntityFrameworkCore;

namespace CC98.TeacherEvaluationSystem.Components
{
	/// <summary>
	/// 部门选择器组件。
	/// </summary>
	public class DepartmentSelectorViewComponent : ViewComponent
	{
		/// <summary>
		/// 初始化组件的新实例。
		/// </summary>
		/// <param name="dbContext">数据库上下文对象。</param>
		public DepartmentSelectorViewComponent(TesDbContext dbContext)
		{
			DbContext = dbContext;
		}

		/// <summary>
		/// 数据库上下文对象。
		/// </summary>
		private TesDbContext DbContext { get; }

		public async Task<IViewComponentResult> InvokeAsync(ModelExpression aspFor)
		{
			var cancellationToken = Request.HttpContext.RequestAborted;

			// 加载所有部门数据
			await DbContext.Departments.LoadAsync(cancellationToken);

			var items = from i in DbContext.Departments
						where i.ParentId == null
						select i;

			ViewBag.ModelFor = aspFor;

			return View(await items.ToArrayAsync(cancellationToken));
		}
	}
}

CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CC98.TeacherEvaluationSystem.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Sakura.AspNetCore;

namespace CC98.TeacherEvaluationSystem.Controllers
{
	/// <summary>
	/// 提供对部门的相关操作。
	/// </summary>
	public class DepartmentController : Controller
	{
		public DepartmentController(TesDbContext dbContext, IOperationMessageAccessor messageAccessor)
		{
			DbContext = dbContext;
			MessageAccessor = messageAccessor;
		}

		/// <summary>
		/// 数据库上下文对象。
		/// </summary>
		private TesDbContext DbContext { get; }

		/// <summary>
		/// 消息访问服务。
		/// </summary>
		private IOperationMessageAccessor MessageAccessor { get; }

		/// <summary>
		/// 显示部门列表。
		/// </summary>
		/// <param name="page">页码。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[AllowAnonymous]
		public async Task<IActionResult> Index(int page = 1, CancellationToken cancellationToken = default)
		{
			var items = from i in DbContext.Departments
						orderby i.Name
						select i;

			return View(await items.ToPagedListAsync(12, page, cancellationToken));
		}

		/// <summary>
		/// 显示管理页面。
		/// </summary>
		/// <param name="page">页码。</param>
		/// <returns>用于取消操作的令牌。</returns>
		[HttpGet]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Manage(int page = 1, CancellationToken cancellationToken = default)
		{
			var items = from i in DbContext.Departments
						orderby i.Name
						select i;

			return View(await items.ToPagedListAsync(12, page, cancellationToken));
		}

		/// <summary>
		/// 显示创建部门界面。
		/// </summary>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[Authorize(Policies.Edit)]
		public IActionResult Create()
		{
			return View();
		}

		/// <summary>
		/// 执行创建部门操作。
		/// </summary>
		/// <param name="model">数据模型。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize(Policies.Edit)]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(Department model, CancellationToken cancellationToken = default)
		{
			await CheckDepartmentRelationshipAsync(model, cancellationToken);

			if (ModelState.IsValid)
			{
				DbContext.Departments.Add(model);

				try
				{
					await DbContext.SaveChangesAsync(cancellationToken);
					MessageAccessor.Messages.Add(OperationMessageLevel.Success, "操作成功",
						string.Format(CultureInfo.CurrentUICulture, "你已经成功添加了部门 {0}", model.Name));

					return RedirectToAction("Index", "Department");

				}
				catch (DbUpdateException ex)
				{
					ModelState.AddModelError(string.Empty, ex.GetBaseMessage());
				}
			}

			return View(model);
		}

		/// <summary>
		/// 显示部门编辑页面。
		/// </summary>
		/// <param name="id">要编辑的部门的标识。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		[HttpGet]
		[Authorize(Policies.Edit)]
		public async Task<IActionResult> Edit(int id, CancellationToken cancellationToken = default)
		{
			var item = await DbContext.Departments.FindAsync(new object[] { id }, cancellationToken);

			if (item == null)
			{
				return NotFound();
			}

			return View(item);
		}

		/// <summary>
		/// 执行编辑部门操作。
		/// </summary>
		/// <param name="model">数据模型。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		[HttpPost]
		[Authorize(Policies.Edit)]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(Department model, CancellationToken cancellationToken = default)
		{
			await CheckDepartmentRelationshipAsync(model, cancellationToken);

			if (ModelState.IsValid)
			{
				DbContext.Departments.Update(model);

				try
				{
					await DbContext.SaveChangesAsync(cancellationToken);
					MessageAccessor.Messages.Add(OperationMessageLevel.Success, "操作成功",
						string.Format(CultureInfo.CurrentUICulture, "你已经成功编辑了部门 {0}", model.Name));

					return RedirectToAction("Index", "Department");

				}
				catch (DbUpdateException ex)
				{
					ModelState.AddModelError(string.Empty, ex.GetBaseMessage());
				}
			}

			return View(model);
		}

		/// <summary>
		/// 查看部门详细信息。
		/// </summary>
		/// <param name="id">部门标识。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		[HttpGet]
		public async Task<IActionResult> Detail(int id, CancellationToken cancellationToken = default)
		{
			var item = await
				(from i in DbContext.Departments
				 where i.Id == id
				 select i)
					.Include(p => p.Children)
					.Include(p => p.Teachers)
					.SingleOrDefaultAsync(cancellationToken);

			if (item == null)
			{
				return NotFound();
			}

			return View(item);
		}

		/// <summary>
		/// 检查部门数据以确保不存在循环上级。
		/// </summary>
		/// <param name="model">数据模型。</param>
		/// <param name="cancellationToken">用于取消操作的令牌。</param>
		/// <returns>操作结果。</returns>
		private async Task CheckDepartmentRelationshipAsync(Department model, CancellationToken cancellationToken)
		{
			var currentId = model.ParentId;
			while (currentId != null)
			{
				if (currentId == model.Id)
				{
					ModelState.AddModelError(string.Empty, "部门之间存在循环上级关系。");
					return;
				}

				var parent = await DbContext.Departments.FindAsync(new object[] { currentId }, cancellationToken);
				currentId = parent.ParentId;
			}
		}
	}
}

CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Views/Department/Create.cshtml
@model Department
@{
	ViewBag.Title = "创建部门";
}

<form asp-controller="Department" asp-action="Create" asp-antiforgery="true" method="post">

	<div class="row justify-content-center">
		<div class="col-12 col-sm-9 col-md-6">

			<partial name="_EditPartial" />

			<hr />
			<div class="text-danger" asp-validation-summary="ModelOnly"></div>
			<button type="submit" class="btn btn-primary">创建部门</button>
			<button type="reset" class="btn btn-outline-secondary">清空填写</button>
		</div>
	</div>


</form>

CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Views/Department/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@model Department
@inject IViewLocalizer ViewLocalizer

@{
	ViewBag.Title = ViewLocalizer["编辑部门 - {0}", Model.Name];
}

<form asp-controller="Department" asp-action="Edit" asp-antiforgery="true" method="post">

	<input asp-for="Id" type="hidden" />

	<div class="row justify-content-center">
		<div class="col-12 col-sm-9 col-md-6">

			<partial name="_EditPartial" />

			<hr />
			<div class="text-danger" asp-validation-summary="ModelOnly"></div>
			<button type="submit" class="btn btn-primary">编辑部门</button>
			<button type="reset" class="btn btn-outline-secondary">撤销更改</button>
		</div>
	</div>

</form>

CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Views/Department/Index.cshtml
@model IPagedList<Department>
@{
	ViewBag.Title = "部门一览";
}

@if (Model.Any())
{

	<div class="row justify-content-center">

		@foreach (var i in Model)
		{
			<div class="col-6 col-sm-4 col-md-3">
				<div class="card text-center">
					<div class="card-body">
						<p class="card-title"><a asp-controller="Department" asp-action="Detail" asp-route-id="@i.Id">@i.Name</a></p>
					</div>
				</div>
			</div>
		}

	</div>

	<hr />
	<pager />
}
else
{
	<p class="text-center text-muted">目前还没有任何部门。请等待管理员添加部门。</p>
}

<authorize policy="@Policies.Edit">
	<hr />
	<a asp-controller="Department" asp-action="Create" class="btn btn-primary">创建部门</a>
</authorize>

CC98.TeacherEvaluationSystem/CC98.TeacherEvaluationSystem/Views/Department/_EditPartial.cshtml
@model Department

<div class="form-group">
	<label asp-for="Name">部门名称</label>
	<input type="text" asp-for="Name" class="form-control" />
	<span class="text-danger" asp-validation-for="Name"></span>
	<small class="form-text text-muted">部门的名称。将会显示在多个页面，也会影响列出多个部门时的排序结果。</small>
</div>
			
<div class="form-group">
	<label asp-for="Description">部门描述</label>
	<textarea row="3" asp-for="Description" class="form-control"></textarea>
	<span class="text-danger" asp-validation-for="Description"></span>
	<small class="form-text text-muted">部门的描述，将会显示在多个页面。</small>
</div>

<div class="form-group">
	<label asp-for="ParentId">上级部门</label>
	<vc:department-selector asp-for="ParentId" />
	<span class="text-danger" asp-validation-for="Name"></span>
	<small class="form-text text-muted">部门所属的上级部门。请注意部门之间不能产生循环上级关系。</small>
</div>